# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: ["main"]
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.event.repository.name }}
  VERSION: ${{ github.run_number }}
  
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code ${{ github.run_number }}
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build, Test, and SonarCloud Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn clean verify sonar:sonar -Dsonar.login=${SONAR_TOKEN}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226       
    - name: Log into registry ${{ env.REGISTRY }}
      if: github.event_name != 'pull_request'
      uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }} 
    - name: Extract Docker metadata ${{ secrets.DOCKERHUB_USERNAME }}
      id: meta
      uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}        
    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
        labels: ${{ steps.meta.outputs.labels }}
    - name: Checkout manifest repo gitOps
      uses: actions/checkout@v4
      with:
        repository: betorosas/gitOps
        token: ${{ secrets.TOKEN }}
        path: gitOps
        ref: main
    - name: Update image tag in manifest (simple YAML edit)
      working-directory: gitOps
      run: |
        # File to edit in Repo B:
        FILE="k8s/restaurant-manifest.yml"
        # Image repo/name (no tag) â€” adjust to yours:
        IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}"
        # New tag:
        NEW_TAG="${{ env.VERSION }}"
        
        sed -i -E "s|(image:\s*${IMAGE_NAME}:)[^[:space:]]+|\1${NEW_TAG}|g" "$FILE"
        echo "Updated $FILE:"
        grep -n "image:" "$FILE" || true

    - name: Commit & push changes to manifest repo
      working-directory: gitOps
      run: |
        git config user.name  "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git status
        # Only commit if there are changes
        if git diff --cached --quiet; then
          echo "No changes to commit."
          exit 0
        fi
          git commit -m "chore: bump image to ${{ steps.vars.outputs.TAG_NO_V }} (from ${{ github.repository }} tag ${{ github.ref_name }})"
          git push origin main        
